# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models, migrations
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client_exit',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('move_out_date', models.DateField(null=True, blank=True, help_text='What date is client moving out of the NSHF program?')),
                ('completed_program', models.BooleanField(default=False, help_text='For what reasons is client leaving the program?')),
                ('wants_to_leave', models.BooleanField(default=False)),
                ('non_payment_of_rent', models.BooleanField(default=False)),
                ('no_employment', models.BooleanField(default=False)),
                ('drug_alcohol_problem', models.BooleanField(default=False)),
                ('exit_reason_other', models.BooleanField(default=False)),
                ('exit_reason_other_text', models.TextField(null=True, blank=True, help_text='for what other reason is client leaving?')),
                ('exit_relationship', models.CharField(choices=[('SINGLE', 'Single'), ('PARTNERED', 'Partnered'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=9, blank=True)),
                ('exit_childcare_county_paid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_primary_childcare_type', models.CharField(choices=[('CENTER', 'Center'), ('FAMILY', 'Family'), ('FRIENDS', 'Friends'), ('OTHER', 'Other'), ('NONE', 'None')], max_length=7)),
                ('exit_level_of_education', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12)),
                ('exit_enrolled_educational', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12, help_text='Is client currently enrolled in educational program?')),
                ('exit_employment_type', models.CharField(choices=[('FULL_W_BEN', 'Full time with benefits'), ('FULL', 'Full time'), ('PART', 'Part time'), ('TEMP_FT', 'Temp full time'), ('TEMP_PT', 'Temp part time'), ('UE', 'Unemployed')], max_length=10)),
                ('exit_employment_sector', models.CharField(choices=[('BUSINESS_SERVICES', 'Business Services'), ('CONSTRUCTION', 'Construction'), ('CUSTOMER_SERVICE', 'Customer Service'), ('EDUCATION', 'Education'), ('FINANCIAL', 'Financial'), ('FOOD_SERVICE', 'Food Service'), ('GOVERNMENT', 'Government'), ('HEALTH_CARE', 'Health Care'), ('INFORMATION', 'Information'), ('LEISURE_HOSPITALITY', 'Leisure and Hospitality'), ('MANUFACTURING', 'Manufacturing'), ('NON_PROFIT', 'Non-profit'), ('OFFICE_ADMIN', 'Office / Administrative'), ('RETAIL', 'Retail'), ('OTHER', 'Other')], max_length=19)),
                ('sector_write_in', models.CharField(max_length=20, blank=True)),
                ('exit_job_hire_date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('exit_average_hours_per_week', models.CharField(choices=[('NONE', 'None'), ('LESS_THAN_25', 'less than 25'), ('25_TO_34', '25 - 34'), ('35_PLUS', '35 +')], max_length=12)),
                ('exit_hourly_wage', models.DecimalField(max_digits=4, decimal_places=2, help_text='Please write just the number of dollars client makes per hour of work.')),
                ('exit_monthly_gross_income', models.DecimalField(max_digits=8, decimal_places=2, help_text='Please write just the amount of gross income client makes in a month.')),
                ('exit_credit_report', models.DateField(help_text='Most recent date client accessed credit report.')),
                ('exit_credit_score', models.IntegerField(help_text='Please enter most recent known client credit score.')),
                ('credit_card_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True, help_text='Please write just the number of dollars client estimates they are in debt.')),
                ('medical_bill_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('car_loan_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('student_loan_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('legal_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('utilities_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('cell_phone_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('pay_day_loan_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('other_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('other_debt_write_in', models.CharField(max_length=30, blank=True, help_text='What other kinds of debt does the client have?')),
                ('exit_total_debt', models.DecimalField(max_digits=10, decimal_places=2, help_text='Total estimated client debt, or sum of above debt')),
                ('exit_receiving_MFIP', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_receiving_WIC', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_receiving_child_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_receiving_unemployment', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_receiving_food_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_receiving_emergency_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_receiving_energy_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_bank_account', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_amount_in_bank', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True, help_text='Please write the amount of dollars client has in bank account.')),
                ('exit_drivers_license', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('exit_car', models.CharField(choices=[('NO_CAR', 'Does not own car'), ('NOT_INSURED', 'Car NOT insured'), ('INSURED', 'Car insured')], max_length=11, help_text='Does client currently own a car, if so is it insured?')),
                ('exit_phone', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, help_text='Does client have working phone that is always on?')),
                ('exit_contact', models.CharField(max_length=20, blank=True, help_text='Best phone number to reach client in the future')),
                ('next_address', models.TextField(null=True, blank=True, help_text='Where will client be living next? Please record address or name of program, building, etc.')),
                ('what_worked', models.TextField(blank=True, help_text='What about this program worked well for you?')),
                ('program_changes', models.TextField(blank=True, help_text='What do you think should change about this program?')),
                ('greatest_success', models.TextField(blank=True, help_text='what does client see as their greatest success while in this program?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client_follow_up',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('date_follow_up', models.DateField()),
                ('year', models.DecimalField(max_digits=4, decimal_places=2)),
                ('follow_up_level_of_education', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12, blank=True)),
                ('follow_up_enrolled_educational', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12, blank=True, help_text='Is client currently enrolled in educational program?')),
                ('follow_up_employment_type', models.CharField(choices=[('FULL_W_BEN', 'Full time with benefits'), ('FULL', 'Full time'), ('PART', 'Part time'), ('TEMP_FT', 'Temp full time'), ('TEMP_PT', 'Temp part time'), ('UE', 'Unemployed')], max_length=10, blank=True)),
                ('follow_up_employment_sector', models.CharField(choices=[('BUSINESS_SERVICES', 'Business Services'), ('CONSTRUCTION', 'Construction'), ('CUSTOMER_SERVICE', 'Customer Service'), ('EDUCATION', 'Education'), ('FINANCIAL', 'Financial'), ('FOOD_SERVICE', 'Food Service'), ('GOVERNMENT', 'Government'), ('HEALTH_CARE', 'Health Care'), ('INFORMATION', 'Information'), ('LEISURE_HOSPITALITY', 'Leisure and Hospitality'), ('NON_PROFIT', 'Non-profit'), ('MANUFACTURING', 'Manufacturing'), ('OFFICE_ADMIN', 'Office / Administrative'), ('RETAIL', 'Retail'), ('OTHER', 'Other')], max_length=19, blank=True)),
                ('follow_up_sector_write_in', models.CharField(max_length=20, blank=True)),
                ('follow_up_receiving_MFIP', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_receiving_WIC', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_receiving_child_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_receiving_unemployment', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_receiving_food_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_receiving_emergency_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_receiving_energy_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('follow_up_housing', models.CharField(choices=[('MRKT_RATE', 'Market rate rental'), ('SECTION_8', 'Section 8'), ('OWN_HOME', 'Own home'), ('FRNDS_FAM', 'With friends or family'), ('SHELTER', 'Shelter'), ('HOMELESS', 'Homeless'), ('PROGRAM', 'Housing program'), ('OTHER', 'Other')], max_length=9, blank=True)),
                ('follow_up_total_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('follow_up_progress', models.TextField(blank=True, help_text='What other progress has client made since leaving the program?')),
            ],
        ),
        migrations.CreateModel(
            name='Client_intake',
            fields=[
                ('client_id', models.AutoField(serialize=False, primary_key=True)),
                ('client_date_of_birth', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('client_first_name', models.CharField(max_length=20)),
                ('client_last_name', models.CharField(max_length=20)),
                ('client_move_in', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('female', models.BooleanField(default=False)),
                ('male', models.BooleanField(default=False)),
                ('transgender', models.BooleanField(default=False)),
                ('another_gender', models.BooleanField(default=False)),
                ('gender_prefer_not_to_say', models.BooleanField(default=False)),
                ('gender_write_in', models.CharField(max_length=200, blank=True)),
                ('black_african_american', models.BooleanField(default=False)),
                ('indigenous_native_american', models.BooleanField(default=False)),
                ('white', models.BooleanField(default=False)),
                ('hispanic_latino', models.BooleanField(default=False)),
                ('asian_pacific_islander', models.BooleanField(default=False)),
                ('multi_racial', models.BooleanField(default=False)),
                ('another_race_ethnicity', models.BooleanField(default=False)),
                ('race_prefer_not_to_say', models.BooleanField(default=False)),
                ('race_write_in', models.CharField(max_length=100, blank=True)),
                ('long_term_homeless', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_relationship', models.CharField(choices=[('SINGLE', 'Single'), ('PARTNERED', 'Partnered'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=9)),
                ('baseline_childcare_county_paid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('baseline_primary_childcare_type', models.CharField(choices=[('CENTER', 'Center'), ('FAMILY', 'Family'), ('FRIENDS', 'Friends'), ('OTHER', 'Other'), ('NONE', 'None')], max_length=7)),
                ('baseline_level_of_education', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12)),
                ('baseline_enrolled_educational', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12)),
                ('baseline_criminal_history', models.CharField(choices=[('NO', 'No'), ('MISDEM', 'Misdemeanor'), ('GROSS', 'Gross Misdemeanor'), ('FELONY', 'Felony')], max_length=6)),
                ('baseline_employment_type', models.CharField(choices=[('FULL_W_BEN', 'Full time with benefits'), ('FULL', 'Full time'), ('PART', 'Part time'), ('TEMP_FT', 'Temp full time'), ('TEMP_PT', 'Temp part time'), ('UE', 'Unemployed')], max_length=10)),
                ('baseline_employment_sector', models.CharField(choices=[('BUSINESS_SERVICES', 'Business Services'), ('CONSTRUCTION', 'Construction'), ('CUSTOMER_SERVICE', 'Customer Service'), ('EDUCATION', 'Education'), ('FINANCIAL', 'Financial'), ('FOOD_SERVICE', 'Food Service'), ('GOVERNMENT', 'Government'), ('HEALTH_CARE', 'Health Care'), ('INFORMATION', 'Information'), ('LEISURE_HOSPITALITY', 'Leisure and Hospitality'), ('MANUFACTURING', 'Manufacturing'), ('NON_PROFIT', 'Non-profit'), ('OFFICE_ADMIN', 'Office / Administrative'), ('RETAIL', 'Retail'), ('OTHER', 'Other')], max_length=19)),
                ('sector_write_in', models.CharField(max_length=20, blank=True)),
                ('baseline_hire_date', models.DateField(help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('baseline_average_hours_per_week', models.CharField(choices=[('NONE', 'None'), ('LESS_THAN_25', 'less than 25'), ('25_TO_34', '25 - 34'), ('35_PLUS', '35 +')], max_length=12)),
                ('baseline_hourly_wage', models.DecimalField(max_digits=4, decimal_places=2)),
                ('baseline_monthly_gross_income', models.DecimalField(max_digits=8, null=True, decimal_places=2, blank=True)),
                ('baseline_monthly_net_income', models.DecimalField(max_digits=8, null=True, decimal_places=2, blank=True)),
                ('baseline_credit_report', models.DateField(null=True, blank=True, help_text='Approximately - when was the last time client accessed a credit report?, if never, enter 9999-99-99')),
                ('baseline_credit_score', models.IntegerField(null=True, blank=True)),
                ('credit_card_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('medical_bill_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('car_loan_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('student_loan_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('legal_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('utilities_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('cell_phone_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('pay_day_loan_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('other_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('other_debt_write_in', models.CharField(max_length=30, blank=True, help_text='What other kinds of debt does the client have?')),
                ('baseline_total_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True, help_text='Total estimated client debt, or sum of above debt')),
                ('baseline_receiving_MFIP', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_receiving_WIC', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_receiving_child_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_receiving_unemployment', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_receiving_food_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_receiving_emergency_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_receiving_energy_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_bank_account', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_amount_in_bank', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True)),
                ('baseline_drivers_license', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('baseline_car', models.CharField(choices=[('NO_CAR', 'Does not own car'), ('NOT_INSURED', 'Car NOT insured'), ('INSURED', 'Car insured')], max_length=11)),
                ('baseline_goals', models.TextField(blank=True, help_text='Where does client want to be in five years?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('baseline_partner_client', models.ManyToManyField(related_name='baseline_partner_client_rel_+', to='nshf_forms.Client_intake', blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Kid',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('child_name', models.CharField(max_length=20)),
                ('child_dob', models.DateField(null=True, blank=True, help_text='Please use the following format: <em>YYYY-MM-DD</em>.')),
                ('child_school', models.CharField(max_length=30, blank=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(null=True, blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='One_month_update',
            fields=[
                ('id', models.AutoField(serialize=False, verbose_name='ID', primary_key=True, auto_created=True)),
                ('date_form_completed', models.DateField(help_text='please use format yyyy-mm-dd')),
                ('month', models.SmallIntegerField()),
                ('current_relationship', models.CharField(choices=[('SINGLE', 'Single'), ('PARTNERED', 'Partnered'), ('MARRIED', 'Married'), ('DIVORCED', 'Divorced'), ('WIDOWED', 'Widowed')], max_length=9, blank=True)),
                ('current_childcare_county_paid', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('current_primary_childcare_type', models.CharField(choices=[('CENTER', 'Center'), ('FAMILY', 'Family'), ('FRIENDS', 'Friends'), ('OTHER', 'Other'), ('NONE', 'None')], max_length=7, blank=True)),
                ('current_level_of_education', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12, blank=True)),
                ('current_enrolled_educational', models.CharField(choices=[('NO_ED', 'NO High School Diploma or GED'), ('HIGH_SCHOOL', 'High School Diploma'), ('GED', 'GED'), ('TECHNICAL', 'Technical Degree or Certification'), ('ASSOCIATES', 'Associates Degree'), ('BACHELORS', 'Bachelors Degree'), ('ADVANCED', 'Advanced Degree')], max_length=12, blank=True, help_text='Is client currently enrolled in an educational program?')),
                ('financial_education', models.DateField(null=True, blank=True, help_text='If completed financial education course, please enter date completed')),
                ('ged_completed', models.DateField(null=True, blank=True, help_text='If completed GED, please enter date completed')),
                ('drivers_license', models.DateField(null=True, blank=True, help_text='If client got drivers license, please enter date here')),
                ('current_employment_type', models.CharField(choices=[('FULL_W_BEN', 'Full time with benefits'), ('FULL', 'Full time'), ('PART', 'Part time'), ('TEMP_FT', 'Temp full time'), ('TEMP_PT', 'Temp part time'), ('UE', 'Unemployed')], max_length=10)),
                ('current_employment_sector', models.CharField(choices=[('BUSINESS_SERVICES', 'Business Services'), ('CONSTRUCTION', 'Construction'), ('CUSTOMER_SERVICE', 'Customer Service'), ('EDUCATION', 'Education'), ('FINANCIAL', 'Financial'), ('FOOD_SERVICE', 'Food Service'), ('GOVERNMENT', 'Government'), ('HEALTH_CARE', 'Health Care'), ('INFORMATION', 'Information'), ('LEISURE_HOSPITALITY', 'Leisure and Hospitality'), ('MANUFACTURING', 'Manufacturing'), ('NON_PROFIT', 'Non-profit'), ('OFFICE_ADMIN', 'Office / Administrative'), ('RETAIL', 'Retail'), ('OTHER', 'Other')], max_length=19, blank=True)),
                ('sector_write_in', models.CharField(max_length=20, blank=True)),
                ('new_hire_date', models.DateField(null=True, blank=True, help_text='If client has started a new job, please enter the hire date')),
                ('job_end_date', models.DateField(null=True, blank=True, help_text='If client has stopped working at a job, please enter the date that job ended.')),
                ('reason_leaving_job', models.CharField(choices=[('QUIT', 'Quit'), ('FIRED', 'Fired'), ('LAID_OFF', 'Laid off'), ('NEW_JOB', 'Got another job'), ('OTHER', 'Other')], max_length=6, null=True, blank=True, help_text='If client is leaving job, what is the reason?')),
                ('reason_leaving_job_text', models.CharField(max_length=40, blank=True)),
                ('current_average_hours_per_week', models.CharField(choices=[('NONE', 'None'), ('LESS_THAN_25', 'less than 25'), ('25_TO_34', '25 - 34'), ('35_PLUS', '35 +')], max_length=12)),
                ('current_hourly_wage', models.DecimalField(max_digits=4, decimal_places=2, help_text='Please write just the number of dollars client makes per hour of work, 0 if unemployed.')),
                ('current_monthly_gross_income', models.DecimalField(max_digits=10, decimal_places=2)),
                ('current_monthly_net_income', models.DecimalField(max_digits=10, decimal_places=2)),
                ('current_credit_report', models.DateField(null=True, blank=True, help_text='Most recent date client accessed credit report.')),
                ('current_credit_score', models.IntegerField(null=True, blank=True, help_text='Please enter most recent known client credit score.')),
                ('current_total_debt', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True, help_text='Total estimated client debt')),
                ('current_receiving_MFIP', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_receiving_WIC', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_receiving_child_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_receiving_unemployment', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_receiving_food_support', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_receiving_emergency_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_receiving_energy_assistance', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3)),
                ('current_bank_account', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True)),
                ('current_amount_in_bank', models.DecimalField(max_digits=10, null=True, decimal_places=2, blank=True, help_text='Please write the amount of dollars client has in bank account.')),
                ('current_car', models.CharField(choices=[('NO_CAR', 'Does not own car'), ('NOT_INSURED', 'Car NOT insured'), ('INSURED', 'Car insured')], max_length=11, blank=True, help_text='Does client currently own a car, if so is it insured?')),
                ('current_phone', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, help_text='Does client have working phone that is always on?')),
                ('rent_paid', models.CharField(choices=[('ON_TIME', 'On time'), ('LATE', 'Late'), ('NOT_PAID', 'Not Paid')], max_length=8)),
                ('subsidy', models.CharField(choices=[('FULL', 'Full Subsidy'), ('PART', 'Partial Subsidy'), ('NO', 'No Subsidy')], max_length=4)),
                ('utilities_paid_on_time', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True, help_text='Did client pay utilities on time this month?')),
                ('other_bills_paid_on_time', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True, help_text='Did client pay all other bills on time this month?')),
                ('county_paperwork_submitted_on_time', models.CharField(choices=[('YES', 'Yes'), ('NO', 'No')], max_length=3, blank=True, help_text='Did client turn in county paperwork on time this month?')),
                ('chemical_dependency', models.BooleanField(default=False, help_text='Has client disclosed a chemical dependency issue this month?')),
                ('mental_health_assessment', models.DateField(null=True, blank=True, help_text='please enter the date client did mental health assessment in format yyyy-mm-dd')),
                ('diagnosis', models.TextField(blank=True, help_text='If client has one or more mental health diagnoses, please enter here')),
                ('other_progress', models.TextField(blank=True, help_text='What other progress have you made since being in this program?')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(null=True, blank=True)),
                ('client', models.ForeignKey(to='nshf_forms.Client_intake')),
                ('current_partner_client', models.ForeignKey(blank=True, related_name='+', null=True, to='nshf_forms.Client_intake')),
                ('new_children', models.ManyToManyField(to='nshf_forms.Kid', blank=True)),
            ],
        ),
        migrations.AddField(
            model_name='client_intake',
            name='children',
            field=models.ManyToManyField(to='nshf_forms.Kid', blank=True),
        ),
        migrations.AddField(
            model_name='client_follow_up',
            name='client',
            field=models.ForeignKey(to='nshf_forms.Client_intake'),
        ),
        migrations.AddField(
            model_name='client_exit',
            name='client',
            field=models.ForeignKey(to='nshf_forms.Client_intake'),
        ),
        migrations.AddField(
            model_name='client_exit',
            name='exit_children',
            field=models.ManyToManyField(to='nshf_forms.Kid', blank=True),
        ),
        migrations.AddField(
            model_name='client_exit',
            name='exit_partner_client',
            field=models.ForeignKey(blank=True, related_name='+', null=True, to='nshf_forms.Client_intake'),
        ),
    ]
